#
# .travis.yml - configuration file for the travis continuous integration service
#
# see https://docs.travis-ci.com/user/languages/php for more hints
#
language: php

php:
  - 7.4
  - 8.0

sudo: false

cache:
  directory:
    - $HOME/.composer/cache/files

script:
  # lint (parallel)
  - find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected' ; test $? -eq 1
  # composer
  - composer install
  # run tests
  - ./bin/phpunit -c ./tests/phpunit.xml.travis

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#wpnxm"
    use_notice: true
    skip_join: true

git:
  depth: 2
